# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.

title: Hoony's Log
description: Document my learning notes.
author: Chung Hoon Hong
email:
twitter_username: hoony
github_username: chunghoony

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be defined by relative or absolute path.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# PaperMod-like settings
params:
  env: production
  title: Hoony's Log
  description: Document my learning notes.
  author: Chung Hoon Hong
  # Header
  header:
    logo:
      text: Hoony's Log
      link: /
    menu:
      - name: Posts
        url: /
        weight: 1
      - name: Archive
        url: /archives
        weight: 2
      - name: Search
        url: /search/
        weight: 3
      - name: Tags
        url: /tags/
        weight: 4
      - name: FAQ
        url: /faq
        weight: 5
